### ISSUE TITLE
CRAB Submission error: cmsRunFailure related to egmPhotonID handling

### ISSUE THREAD

**Issue by uzzielperez** [cms-exotica-diphotons/diphoton-analysis#13]
Crab submission cmsRun Failure related to egmPhotonID handling. I get a similar error trying to run locally. 
Could be related to this? https://github.com/uzzielperez/diphoton-analysis/blob/2d6eab396964c42c3a556ca669e6bc9c6b928139/ExoDiPhotonFakeRateAnalyzer/plugins/ExoDiPhotonFakeRateAnalyzer.cc#L116

```
Jobs status:                    failed                  100.0% (4/4)

No publication information available yet

Error Summary:

2 jobs failed with exit code 8001:

        1 jobs failed with following error message: (for example, job 4)

                CmsRunFailure
                CMSSW error message follows.
                Fatal Exception
                An exception of category 'MultiTokenTException' occurred while
                   [0] Processing  Event run: 1 lumi: 106 event: 86241 stream: 0
                   [1] Running path 'p'
                   [2] Prefetching for module ExoDiPhotonFakeRateAnalyzer/'diphoton'
                   [3] Prefetching for module VersionedPhotonIdProducer/'egmPhotonIDs'
                   [4] Calling method for module PhotonIDValueMapProducer/'photonIDValueMapProducer'
                Exception Message:
                Neither handle is valid!

        1 jobs failed with following error message: (for example, job 3)

                CmsRunFailure
                CMSSW error message follows.
                Fatal Exception
                An exception of category 'MultiTokenTException' occurred while
                   [0] Processing  Event run: 1 lumi: 537 event: 440603 stream: 0
                   [1] Running path 'p'
                   [2] Prefetching for module ExoDiPhotonFakeRateAnalyzer/'diphoton'
                   [3] Prefetching for module VersionedPhotonIdProducer/'egmPhotonIDs'
                   [4] Calling method for module PhotonIDValueMapProducer/'photonIDValueMapProducer'
                Exception Message:
                Neither handle is valid!

2 jobs failed with exit code 139:

        2 jobs failed with following error message: (for example, job 1)

                CmsRunFailure

Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.
```

**Comment by uzzielperez** [comment]
It runs when I comment out the `applyEnergyCorrections` and `applyVIDOnCorrectedEgamma`. Is there a setup so that this works correctly?

```
setupEgammaPostRecoSeq(process,
                       #applyEnergyCorrections=True,
                       #applyVIDOnCorrectedEgamma=True,
                       runVID=True,
                       runEnergyCorrections=True,
                       era=egm_info['era'])
```

**Comment by christopheralanwest** [comment]
> It runs when I comment out the `applyEnergyCorrections` and `applyVIDOnCorrectedEgamma`. Is there a setup so that this works correctly?
> 
> ```
> setupEgammaPostRecoSeq(process,
>                        #applyEnergyCorrections=True,
>                        #applyVIDOnCorrectedEgamma=True,
>                        runVID=True,
>                        runEnergyCorrections=True,
>                        era=egm_info['era'])
> ```

This will result in the corrections not being applied by default, which is not what we want. The problem is a change in the EGM code needed for 10_6_X. I updated the README instructions at https://github.com/cms-exotica-diphotons/diphoton-analysis/commit/11c96fff75674053ddfc09ece1d6b4d8330a6202 to revert the latest set to changes. With those changes, I am able to run on data without any problems:

`cmsRun diphoton_fakeRate_cfg.py inputFiles=file:/uscms/home/cawest/nobackup/EGamma_Run2018A-17Sep2018-v2_D0C18EBB-8DD7-EC4F-9C1B-CA3EAD44D993.root`

This analyzer is only used for data and is not intended to be run on MC. So, for example, flags such as `Flag_eeBadScFilter` will be missing in MC.

**Comment by uzzielperez** [comment]
Thanks, Chris! I think we can close this issue.
